### ISSUE TITLE
1/10 ведра лавы, горит дольше чем просто 100mb лавы в бойлере

### ISSUE THREAD

**Issue by Yorodoshi** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#100]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Сервер|Одиночная 

### Новые миры

Да

### Ожидаемое поведение

Я думал что 100mb лавы будет гореть 1,25 с, а не всего 0,35 с... 

### Фактическое поведение

![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/1167554b-7232-49d1-81b4-a89545e0e891)
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/d44a47d4-517c-4a3a-9f64-a4d546ca1b0c)

### Действия по воспроизведению

Вот так

### Дополнительная информация

Предлагаю изменить время горения 100mb лавы без ведра на 1.25 секунд, чтобы было такое-же как у ведра лавы

**Comment by FriendlyCube** [comment]
вообще это грег разрабы  должны фиксить

**Comment by Yorodoshi** [comment]
> вообще это грег разрабы должны фиксить

Если мы не будем вмешиваться в грег, тогда надо удалить бредовый крафт машин кейсинга, обратно добавить бронзовую доменку и т.п.

**Comment by FriendlyCube** [comment]
нет, возвращать не надо, но стоит сообщить грег разрабам об этом шобы такого прикола не было

**Comment by SpeeeDCraft** [comment]
Нельзя удалить или изменить рецепт бойлера при помощи KubeJs, нужно разрабам написать.
