### ISSUE TITLE
Trip hammer не работает с молотами GT

### ISSUE THREAD

**Issue by a22kat** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#102]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

сервер

### Новые миры

Да

### Ожидаемое поведение

-

### Фактическое поведение

В trip hammer нельзя вставить молот gregtech.

![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/60256920/dd95a538-fe53-4cbe-93b3-308866754f2d)

### Действия по воспроизведению

-

### Дополнительная информация

-

**Comment by SpeeeDCraft** [comment]
Этот блок был удален в сборке, так что закрываю
