### ISSUE TITLE
Опять проблемы с многомодовыми слитками

### ISSUE THREAD

**Issue by Yorodoshi** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#105]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Сервер|Одиночная 

### Новые миры

Да

### Ожидаемое поведение

Что получиться слиток стали из грега

### Фактическое поведение

![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/4d32499d-bfae-4e55-829e-89530f44dcc5)

### Действия по воспроизведению

Получились они после того как я высунул их из литейных форм под слитки

### Дополнительная информация

Ещё прикол в том, что в JEI этих слитков не существует
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/d1079824-88c5-42cf-94b1-cc6269094e4b)

**Comment by SpeeeDCraft** [comment]
Мда, в курсе проблемы, причем уже поправили даже, патч надеюсь сегодня
