### ISSUE TITLE
Нет рецепта дробления кирпича

### ISSUE THREAD

**Issue by Yorodoshi** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#106]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Сервер|Одиночная 

### Новые миры

Да

### Ожидаемое поведение

![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/cad4c41a-2e26-4bfa-87c2-9511fc2bfe8f)
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/19c36b0d-0d93-4b84-aa96-c2c1fa935236)

### Фактическое поведение

![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/f8a28367-3211-4030-ab44-c47a6f7ee6e6)

### Действия по воспроизведению

Рецепта нет (

**Comment by a22kat** [comment]
Блоки делай. Они дробятся.

**Comment by SpeeeDCraft** [comment]
Дурка, фляга свестит
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/52341158/ab924beb-34b2-4d80-a02d-f5901af30332)
