### ISSUE TITLE
Обработка слитков на молоте

### ISSUE THREAD

**Issue by Yorodoshi** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#107]
### Версия используемого модпака

0.1.2

### Связанная проблема

Почему тяжёлый паровой молот может выковать пластину напрямую из слитков, и при этом не может просто взять и обработать слитки.
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/c3a71e70-8e3a-4e5f-a2ac-472859f5fda4)

### Ваше решение

Предлагаю добавить рецепты обработки в "Кузнечный молот" следующих слитков:
Крица -> Кричное железо -> Кованное железо
Белый чугун -> Высокоуглеродистая сталь -> Сталь
Сырая сталь + белый чугун -> Высокоуглеродистая чёрная сталь -> Чёрная сталь
Сырая синяя сталь + чёрная сталь -> Высокоуглеродистая синяя сталь -> Синяя сталь
Сырая красная сталь + чёрная сталь -> Высокоуглеродистая красная сталь -> Красная сталь

**Comment by SpeeeDCraft** [comment]
Это ты хорошо, подметил, на 1.12 такое было, тут тоже сделаем
