### ISSUE TITLE
Адаптировать рецепты крафта из Exposure (мод на фотографию)

### ISSUE THREAD

**Issue by Yorodoshi** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#109]
### Версия используемого модпака

0.1.2

### Связанная проблема

Есть крафты проявления фотоплёнки, где используется неполучаемые ингредиенты:
Мутное зелье (адские бородавки). И сушёные ламинарии. 
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/d257f985-b19d-4958-9d95-099017e223a9)
Да и цветная фотография только после HV не очень прикольно, т.к. этот мод это ТОЛЬКО декор, который должен быть доступен на относительно ранних этапах игры(пар/lv) .
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/2f71eb4c-e1ba-48a6-acb7-5a563b39409b)

### Ваше решение

Предлагаю изменить крафты:
1. Заменить сушёную ламинарию на бумагу в обоих крафтах, заменить лазурит синим красителем:
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/f50de8eb-9e00-4528-98ce-bbd9c98e64ca)
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/1c39edb7-405e-4b5e-b651-2f46a2019ecb)

2. ЧБ фотографии оставить как оно есть, проявлять водой, ибо оно так и было по началу, но добавить разные ёмкости для воды (вёдра, фляги и т.п.)
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/9127f5f7-03c7-41d3-b641-fc3032552195)

3. Цветные совершенно переработать, оставить воду, добавить сульфид натрия(Na2S), обычную соль(NaCl) и серебряную пыль(Ag), чтобы хоть как-то оно шло в реализм.
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/08b1d785-48de-4feb-a07e-b3722f0ddb42)
Остальные крафты оставить как есть, ибо это декор мод, не требующий усложнений !

### Дополнительная информация

Мод очень крутой и красивый, хочу цветную фотографию на сервер !!
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/bcc6d566-0c73-4efa-a754-f880026ebf02)

**Comment by Yorodoshi** [comment]
@FriendlyCube  фиксани. 2 крафта все-лишь и минус 1 ишью сразу

**Comment by FriendlyCube** [comment]
пока обновы не будетБ всё равно не получишь ничего

**Comment by Yorodoshi** [comment]
> пока обновы не будетБ всё равно не получишь ничего

Почему мы ждём 0.1.3 дольше чем 0.1.0 ?

**Comment by FriendlyCube** [comment]
стоп,так крафты работают

**Comment by FriendlyCube** [comment]
а вижу

**Comment by FriendlyCube** [comment]
изменб только крафт не создоваемых крафтов, остальное оставлю, в каменном веке ты не будешь делат ьцветные фотографии

**Comment by So0vey** [comment]
Просто добавь линзу в крафт

**Comment by So0vey** [comment]
Или сложные формы, которые делаются на экструдере
