### ISSUE TITLE
Изменить цвета металлов.

### ISSUE THREAD

**Issue by So0vey** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#113]
### Версия используемого модпака
Файл со всей цветовой палитрой :
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/127132701/82d6b306-b0c4-4c42-8cef-8da7fbf66556)

-47

### Связанная проблема

Цвета металлов из тфк и грега отличаются:

### Ваше решение

Перенести цвета материалов из тфк в грег теч

**Comment by SpeeeDCraft** [comment]
Я считаю, что это можно закрыть, тк мы сделали некоторые текстуры для сырых кусков похожими на гт + металлы тфк которые остались не дублируют грег, поэтому говорить о их цвете более не требуется.
