### ISSUE TITLE
Редактировать крафты с нитками

### ISSUE THREAD

**Issue by Yorodoshi** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#117]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Сервер|Одиночная 

### Новые миры

Да

### Ожидаемое поведение

'

### Фактическое поведение

![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/0e75242d-dd5a-4d9d-af10-2a9cba292f15)
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/8d79d131-b0ae-4ed1-aa2d-96d010c33a26)
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/c49c3c0d-310a-48c5-982f-9f468ccdb302)
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/7e2d5d95-37b4-4eec-8d68-fae2e0493f34)
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/3e1f1131-824f-488c-8ab8-e895ab8ca498)

### Действия по воспроизведению

'

### Дополнительная информация

Сделать крафты со всеми видами ниток в рецепте в ассемблере, вещей из All-In-One, Macaw's Mods for TerraFirmaCraft + удалить старый рецепт пушки с двойными чугунными листами(которые невозможны для крафта)

**Comment by FriendlyCube** [comment]
ок
