### ISSUE TITLE
крафт, исус))

### ISSUE THREAD

**Issue by BABOOBABA** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#127]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

норм

### Новые миры

Да

### Ожидаемое поведение

нормальное

### Фактическое поведение

https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/150588951/e3192aa6-c844-4394-88c9-058999ab8338

### Действия по воспроизведению

да

**Comment by SpeeeDCraft** [comment]
Название и описание научись писать
