### ISSUE TITLE
вертикальные полу блоки и ступеньки или просто Additional Placements

### ISSUE THREAD

**Issue by BABOOBABA** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#129]
### Версия используемого модпака

да

### Связанная проблема

ну, хотелось бы увидеть вертикальные полублоки и ступеньки

### Ваше решение

добавить Additional Placements
https://www.curseforge.com/minecraft/mc-mods/additional-placements

### Дополнительная информация

![изображение](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/150588951/e1c77706-9060-4101-9423-83640f0fe718)

https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/150588951/ad8ead5e-3fb2-4819-95b4-7d6ed462e5dd

**Comment by SpeeeDCraft** [comment]
Добавлен, будет в 0.4
