### ISSUE TITLE
Добавьте крафт формочек!

### ISSUE THREAD

**Issue by So0vey** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#133]
### Версия используемого модпака

Последняя

### Связанная проблема

Я хочу делать формочки для своей кринже-доменки на станке, но нельзя, единственное, что я могу это вручную месить глину: 
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/127132701/06df0066-c422-486b-b7f6-2b34cb3ce7c4)

### Ваше решение

сделайте крафт через машины гречки

**Comment by C0ffo** [comment]
Закибербулили мажорчика 
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/151227314/4bcc2a99-4801-4898-bfa5-cd12de63616f)
Хотя я помню вроде такая штука была на 1.12.2 ......
или там только горшки с глины были?
