### ISSUE TITLE
Генератор булыги работает. 

### ISSUE THREAD

**Issue by So0vey** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#135]
### Версия используемого модпака

Последняя

### Связанная проблема

Лава+Вода

### Ваше решение

![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/127132701/49e73523-5e55-46d8-842d-dd2bf34f22b3)
Снести это к чертям

### Дополнительная информация

Upd. Получается риолит. Возможно и не такая огромная проблема.
_No response_

**Comment by FriendlyCube** [comment]
если убрать ген булыжника при этом ивенте то тогда возникнет ряд проблем. например, когда ты будешь плавать по рекам, лава , стекающая в реку будет касаться воды без создания среднег7о слоя, то есть будет чтото такое: 
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/112543401/8da9001c-01e5-4be2-85d7-653a6f28ee40)

**Comment by FriendlyCube** [comment]
ген булыги не большая проблема в мире где блоки воды и лавы при растекании не исчезают

**Comment by SpeeeDCraft** [comment]
Это же базовая механика, разве не?

**Comment by So0vey** [comment]
Фигню написал я
