### ISSUE TITLE
Мы добыли ванильный булыжник. Часть 2.

### ISSUE THREAD

**Issue by So0vey** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#136]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Официальный сервер

### Новые миры

Да

### Ожидаемое поведение

Ожидалось, что в сборке булыжник вырезан. Но:

### Фактическое поведение

Вот эта штука: 
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/127132701/e48b29ad-c1af-43ad-81a5-85dc5fd5b180)
Копает руды. И на их место ставит обычный булыжник .
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/127132701/e4282910-7a2c-4b08-96f2-5e83d0c8da11)

### Действия по воспроизведению

Выше все описано

### Дополнительная информация

Предлагаю заменить булыжник на блок глины. Она встречается во всех биомах.

**Comment by FriendlyCube** [comment]
Лол

**Comment by FriendlyCube** [comment]
Нет, будет булыга из базальта

**Comment by So0vey** [comment]
окей, я просто предложил что-то бесполезное, что появляется во всех биомах
