### ISSUE TITLE
Око эндера?

### ISSUE THREAD

**Issue by So0vey** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#139]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Официальный сервер

### Новые миры

Да

### Ожидаемое поведение

![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/127132701/519b061a-89a1-4441-a4e7-3b98ac34db47)
Это так не должно быть

### Фактическое поведение

Это есть

### Действия по воспроизведению

Я никогда такого не хотел
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/127132701/e7c32c59-a7eb-4023-83ed-aa73ad4401e7)
![Uploading image.png…]()

**Comment by FriendlyCube** [comment]
посмотри его крафт просто

**Comment by FriendlyCube** [comment]
это какой вольтаж

**Comment by FriendlyCube** [comment]
и пиши норм исуе

**Comment by So0vey** [comment]
Ладно, я прекрасно понимаю, что еще не дошла разработка до этого, поэтому ишью прикрою, потом перепишу
