### ISSUE TITLE
Коса не работает так как надо 

### ISSUE THREAD

**Issue by Neon4301** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#146]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Сервер

### Новые миры

Да

### Ожидаемое поведение

коса должна работать в области 3х3

### Фактическое поведение

-

### Действия по воспроизведению

-

**Comment by SpeeeDCraft** [comment]
https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/issues/153
