### ISSUE TITLE
Некоторые шахтёрские молоты не имеют NBT-тега AOE, из-за чего они не копают в 3х3

### ISSUE THREAD

**Issue by messAround48** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#148]
### Версия модпака

0.2.0

### Среда запуска

Сервер Forge

### Новые миры

Да

### Ожидаемое поведение

Все шахтёрские молоты копают в 3х3

### Фактическое поведение

Не все шахтёрские молоты копают в 3х3 (медный, чёрная и висмутовая бронза, чёрная сталь)

### Действия по воспроизведению

Попробовать копать этими молотами камень

### Дополнительная информация

Следующие инструменты:
```
gtceu:black_bronze_mining_hammer
gtceu:black_steel_mining_hammer
gtceu:copper_mining_hammer
gtceu:bismuth_bronze_hammer
```
не имеют NBT-тега forge:tools/aoe, из-за чего они не копают в 3х3

**Comment by SpeeeDCraft** [comment]
Исправлено в #149 149
