### ISSUE TITLE
Баг с Crankshaft

### ISSUE THREAD

**Issue by a22kat** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#150]
### Версия модпака

0.2.0

### Среда запуска

сервер

### Новые миры

Да

### Ожидаемое поведение

-

### Фактическое поведение

В crankshaft вставляется gt steel rod. После слома выпадает steel rod из tfc, который нельзя поставить обратно.
![Снимок экрана 2023-12-15 143557](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/60256920/2a84a9ee-073e-409e-967b-6ea87d4f5087)
![Снимок экрана 2023-12-15 143607](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/60256920/a1a92440-d06a-438b-97b0-77b92be1f6ec)

### Действия по воспроизведению

-

**Comment by SpeeeDCraft** [comment]
Этот прекрасный механизм будет отключен в след. версии, из-за отсутствия совместимости с Create, рецепты этой штуки заменятся машинами Create.

**Comment by a22kat** [comment]
> Этот прекрасный механизм будет отключен в след. версии, из-за отсутствия совместимости с Create, рецепты этой штуки заменятся машинами Create.

Create сможет двигать меха?

**Comment by SpeeeDCraft** [comment]
Не уверен

**Comment by SpeeeDCraft** [comment]
Механизм и его рецепт удален из tfc, так как механич. энергия тфк != креейтовской, ждем аддон для совместимости тфк и креейт

**Comment by a22kat** [comment]
Блин, ну нафига? Они так классно автоматом воздух в тигли поддували.
