### ISSUE TITLE
Расширения криейт + интеграция в грегтеч

### ISSUE THREAD

**Issue by So0vey** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#151]
### Версия используемого модпака

Зачем здесь этот вопрос?

### Связанная проблема

Предлагаю разработчикам ознакомится со следующими дополнениями для Create, которые в перспективе можно интегрировать в грегтеч.
Create: The Factory Must Grow
https://www.curseforge.com/minecraft/mc-mods/create-industry
Видео: https://www.youtube.com/watch?v=mZyoONDZqtQ&t
Краткое описание: В перспективе может заменить одноблочные механизмы и многоблочные неказистые механизмы грегтеч. Блинб, вы только посмотрите на эти генераторы внутреннего сгорания и ректификационную колонну.

Create: New Age
https://legacy.curseforge.com/minecraft/mc-mods/create-new-age
Видео: https://youtu.be/z2vnWVJRK78?si=y2Jl-PNCVgpOk1nT
Офигеть, генерация электрической энергии из кинетической энергии. Базированные провода и ядерный реактор. 

### Ваше решение

1

**Comment by SpeeeDCraft** [comment]
Я сам хочу провода, которые представлены в Create или IE, правда разраб ГТ вчера мне чирканул, что такое он делать не будет, а использование проводов IE / Create упразднит систему ампер и энергии как таковой, поэтому я скорее всего буду делать аддон, который умеет в висячие провода с амперами и другой греговской херней. Короче да, надо.
