### ISSUE TITLE
Inscriber Presses from AE2 are consumed in the craft

### ISSUE THREAD

**Issue by Andrei-Mudrov-archmage** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#154]
### Are you using the latest available version?

Yes

### Environment

Server

### New Worlds

No

### Expected Behavior

Inscriber Presses from AE2 are not consumed in the craft

### Actual Behavior

Inscriber Presses from AE2 are consumed in the craft

### Steps to Reproduce

1) Put Silicon and Inscriber Silicon press into the Forming press

### Additional Information

![Снимок экрана (176)](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/44801908/9c1e4830-e446-4f3b-a1ba-b0988e0cb811)
![Снимок экрана (175)](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/44801908/d24c93c4-1ee9-40e0-abfe-259fa9073ab8)

**Comment by So0vey** [comment]
эу, тут разрабы русские, ты че

**Comment by Andrei-Mudrov-archmage** [comment]
> эу, тут разрабы русские, ты че

u menya net ruskoy raskladki

**Comment by SpeeeDCraft** [comment]
Исправлено
