### ISSUE TITLE
Добавление модов HT's TreeChop, Butcher's Delight/Butcher's Delight Foods, Farmer's Delight

### ISSUE THREAD

**Issue by Thomasx0** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#155]
### Версия используемого модпака

1.20

### Ваше решение

Доброго дня.
Предлагаю добавить мод [HT's TreeChop](https://www.curseforge.com/minecraft/mc-mods/treechop) Добавляющий механику рубки дерева похожую на ту что была в версии 1.12 многократно разбивая один блок.
Так прошу рассмотреть интерграцию модов [Butcher's Delight](https://www.curseforge.com/minecraft/mc-mods/butchers-delight) [Butcher's Delight Foods](https://legacy.curseforge.com/minecraft/mc-mods/butchers-delight-foods)
В [Farmer's Delight](https://www.curseforge.com/minecraft/mc-mods/farmers-delight) можно переработать много рецептов подходящих под стиль тфк, разделывать мясо из бутчер на разделочной доске. Делать лапшу из теста тфк. Получать обтесанное бревно и кору дерева. В общем много чего можно полезного сделать.
Можно уже готовые рецепты позаимствовать из сборки Terrafirmacraft-hardrock. 
![cut](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/153584223/551d0d09-2a51-484b-8826-c39d9d017f23)

**Comment by So0vey** [comment]
Ненада нам механик рубки, как в 1.12. HT's TreeChop харам

**Comment by Thomasx0** [comment]
Как по заказу подъехал мод интеграция [Farmer's Delight TFC](https://www.curseforge.com/minecraft/mc-mods/farmers-delight-tfc ) адаптирует Farmers Delight к миру TerrafirmaCraft.

**Comment by SpeeeDCraft** [comment]
https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/issues/157
Теперь здесь весь список, чтобы не потерять

**Comment by SpeeeDCraft** [comment]
Ладно, я шизик, переоткрываю, инфа будет в Projects

**Comment by BABOOBABA** [comment]
Butcher's Delight/Butcher's Delight Foods пиздец

**Comment by SpeeeDCraft** [comment]
Проверили все моды, которые были здесь описаны и предложены на добавление.

HT TreeChop - ставить не будем, так как в будущем есть планы поставить DynamicTrees.

Butcher's Delight - Мод абсолютно не доработан и работает как гавно и не имеет поддержки TFC.

Butcher's Delight Foods - Очередной говномод, который не доделали и логично не сделали не какой поддержки для других модов, для TFC тем более.

Farmers Delight - Хороший мод, но из него нам нужна только еда, скрывать или удалять рецепты всего остального очень долго, по факту все механики уже есть в TFC и +/- еда будет добавлена в FirmaLife, поэтому надобности в этом моде нет.

Farmers Delight TFC - очередной говномод, разраб его позиционирует как мод на совместимость, правда ее там нет, если ставить этот мод с прошлым, добавит в наш модпак больше костылей, короче минус.

И того имеем, что разрабы как обычно наговномодили, а юзеры едят.
