### ISSUE TITLE
Добавление мода Barrels 2012

### ISSUE THREAD

**Issue by Thomasx0** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#156]
### Версия используемого модпака

1.20

### Ваше решение

Кхм. Я тут опять с добавлением мода в сборку. Можно добавить прям в следующий апдейт.
[Barrels 2012](https://www.curseforge.com/minecraft/mc-mods/barrels-2012) Добавляет возможность как и в старом моде носить на спине бочки, вазы, наковальни. Работает все из коробки.

**Comment by SpeeeDCraft** [comment]
Уже добавлен в дев версии, будет в след обновлении
