### ISSUE TITLE
Перестали работать крафты лодок из ТФК и кораблей SmallShips/TFS + нельзя в них сесть

### ISSUE THREAD

**Issue by ExpectoAmogus** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#159]
### Версия модпака

0.3.0

### Среда запуска

офф сервер

### Новые миры

Да

### Ожидаемое поведение

Ожидал, что смогу сесть в свой корабль/лодку и радоваться

### Фактическое поведение

Не смог интерактить со своим кораблем, также отвалились крафты, хз как показать, типо того:
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/72547132/da021627-2d00-4662-9c31-cad61e86a135)

### Действия по воспроизведению

попробуйте сесть в корабль

### Дополнительная информация

Есть вариант, что эта дичь произошла изза нового мода Firma: Civilization, ибо там тоже есть лодки, но в них можно сесть

**Comment by SpeeeDCraft** [comment]
Верное поведение, в след. патче эти корабли будут удалены и заменены на более функциональные.
