### ISSUE TITLE
Антигриф система жесткая

### ISSUE THREAD

**Issue by FriendlyCube** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#17]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

сервер

### Новые миры

Да

### Ожидаемое поведение

![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/112543401/dc3d8cc8-977e-4406-be7f-475804213b6d)
 
 кароч надо антигриф систему упростить, вода не может попасть в приват чанк(как в правой дырке), но если она текла в чанке до того как чанк заприватели(как в левых канавах), то всё норм
 
=

### Фактическое поведение

123

### Действия по воспроизведению

123

**Comment by SpeeeDCraft** [comment]
Ты хочешь натыкать везде проверок лютейших, чтобы сервак падал? Я сделаю проще, тот кто будет графферить будет забанен. А если такого будет много, то просто сделаем сервак по проходке за бабки, звучит

**Comment by SpeeeDCraft** [comment]
Еще меня удивляет, что ты не предлагаешь решение, короче сиди там и не выпендивайся.

**Comment by FriendlyCube** [comment]
да не, я просто констатирую факт, антигриф система душная надо шото делать
