### ISSUE TITLE
Баг Пати (Party bug)

### ISSUE THREAD

**Issue by Latom-alex** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#18]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Сервер

### Новые миры

Да

### Ожидаемое поведение

После РР мы с другом пришли на базу и оказалась делема что друг не может ничего открывать \ ломать на базе хотя Пати мы делали.

### Фактическое поведение

Оказывается после Рестарта сервера скидывается Party из-за чего приходится заново прописывать создание Пати, это крайне мешает кооп выживанию т.к если нету хозяина региона то и ты ничего не сможешь сделать. и тебе придётся ждать хозяина пока тот зайдёт и создаст пати заново.

### Действия по воспроизведению

Проверить можно создав Пати до РР и потом сделать РР и проверить

**Comment by SpeeeDCraft** [comment]
Исправлено в 0.0.6
