### ISSUE TITLE
Полетела текстура при создании оголовья для орудия при использовании камня Mossy Loosy Limestone Rock

### ISSUE THREAD

**Issue by SantaRiver** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#22]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Локально развернутый сервер Forge 1.20

### Новые миры

Да

### Ожидаемое поведение

Будет норм текстура

### Фактическое поведение

![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/48448071/756d46da-94ec-401b-acbd-14c3ad7f208f)

### Действия по воспроизведению

Создания оголовья

**Comment by SpeeeDCraft** [comment]
Проблема TFC, они о ней знают и уже починили в dev

**Comment by SpeeeDCraft** [comment]
Исправлено в 0.0.5, закрываю.
