### ISSUE TITLE
Нету крафта bloomery and blast furnace,так же нету крафта двойных пластин

### ISSUE THREAD

**Issue by C0ffo** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#28]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Официальный сервер ТФГ

### Новые миры

Да

### Ожидаемое поведение

![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/151227314/c074120f-ced5-4730-b843-eb38c00f8507)

### Фактическое поведение

![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/151227314/2659cd37-7c36-4fd1-8e77-2246d14bf9ad)
 (Типа кликаю и не кликается нифига)
 Так же нету нигде крафта двойных пластин для bloomery

### Действия по воспроизведению

Попытатся скрафтить bloomery и blust furnace
или же скрафтить двойную бронзовую пластину

**Comment by SpeeeDCraft** [comment]
Исправлено в dev, будет в след. обновлении.
