### ISSUE TITLE
Медный топор рубит медленеё чем каменный

### ISSUE THREAD

**Issue by C0ffo** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#29]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Официальный сервер ТФГ

### Новые миры

Да

### Ожидаемое поведение

Должен был рубить быстрее

### Фактическое поведение

Не рубит быстреё,в 2-3 медленеё по ощущениям

### Действия по воспроизведению

Сделать каменный и медный топор и проверить скорость рубки

**Comment by C0ffo** [comment]
Кстати медная лопата так же медленеё копает

**Comment by SpeeeDCraft** [comment]
Исправлено в dev, будет в некст версии
