### ISSUE TITLE
Пропал крафт формы из глины (Топор)

### ISSUE THREAD

**Issue by Latom-alex** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#30]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Сервер

### Новые миры

Да

### Ожидаемое поведение

Вы куда украли крафт топора? Мы чё каменными должны всё ломать??

### Фактическое поведение

.

### Действия по воспроизведению

Чек крафт формы топора (ее нет)

**Comment by SpeeeDCraft** [comment]
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/52341158/3ee43b01-7c93-479d-9418-19f0a28c5518)
Шиза?

**Comment by Latom-alex** [comment]
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/150847107/7dfd6163-38b1-4e48-a717-fdcec942f08e)

Это ты шиз
