### ISSUE TITLE
Халькопиритовую руду нельзя сплавить в медь как на 1.12.2

### ISSUE THREAD

**Issue by C0ffo** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#32]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Официальный сервер ТФГ

### Новые миры

Да

### Ожидаемое поведение

Ожидал что сплавлю халькопирит и получу медь

### Фактическое поведение

Засовывал в сосуд и ждал но результата 0
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/151227314/3c65aefb-0eea-423d-91b9-9251bb99c76c)

### Действия по воспроизведению

Попытатся сплавить халькопирит

**Comment by SpeeeDCraft** [comment]
Исправлено в dev, будет в след. обновлении.
