### ISSUE TITLE
Не плавится олово (кассетеритовый песок)

### ISSUE THREAD

**Issue by Latom-alex** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#33]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Сервер

### Новые миры

Да

### Ожидаемое поведение

![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/150847107/c4122546-c6f7-4a73-94ca-072006f05b35)

У кассетерита нет крафта в угольной яме или тигле (по факту крафт только механический или ванильны через печки)
Хотя опять-же примесь чистая должна выплавляться в олово

### Фактическое поведение

.

### Действия по воспроизведению

.

**Comment by SpeeeDCraft** [comment]
Исправлено в dev, будет в след. обновлении.
