### ISSUE TITLE
Очень медленная плавка Руды внутри сосуда который лежит в кузне

### ISSUE THREAD

**Issue by Latom-alex** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#34]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Сервер

### Новые миры

Да

### Ожидаемое поведение

Проблема заключается в том что если положить руду в сосуд и положить это в кузню, то по какой-то причине он плавится очень медленно и на всё уходит примерно 10-15 угля что реально много.
В отличие от слитков которые раскаляются в 3-5 раза быстрей чем сам Сосуд с рудой внутри

### Фактическое поведение

,

### Действия по воспроизведению

Делаем Кузню - Кладём сосуд с рудой внутри в кузню и смотрим (засекаем время нагрева)
Теперь берём 2-рой сосуд с рудой кладём его в Яму засыпаем сеном и брёвнами ждём 8 минут - достаём Сосуд с расплавленной рудой - охлаждаем его и кладём в кузню - видим результат того что этот сосуд с затвердевшей рудой внутри греется в 3-4 раза быстрей, нежели сосуд который мы клали изначально с рудой что-бы она расплавилась в кузне а не в яме. 

Если плавим руду внутри сосуда в кузне - плавится 4-5 раза **ДОЛЬШЕ**
Плавим руду внутри сосуда которая уже была расплавлена до этого в кузне - плавится в 4-5 раза **БЫСТРЕЙ**

**Comment by Yorodoshi** [comment]
В микроволновку засунь кружку с 250мл воды, посчитай за сколько закипит, а потом с 50мл, они одинаково греться что-ли будут ? Плавиться тем дольше, чем больше "масса" объекта.

**Comment by Yorodoshi** [comment]
Про то что расплавленная плавиться быстрее, безусловно, там же тепло тратится и на химическое "восстановление", всё предельно логично
