### ISSUE TITLE
Нету крафта ванильной печки,нужна для steam boiler

### ISSUE THREAD

**Issue by C0ffo** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#35]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Официальный сервер ТФГ

### Новые миры

Да

### Ожидаемое поведение

Смотрел крафты steam boiler и кликаю на крафт печки а она только через машины GT

### Фактическое поведение

![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/151227314/d789eb12-443d-47b9-a529-5214a7e0674a)
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/151227314/dece3665-24b0-4e85-bfc8-d1a9a39f17f1)

### Действия по воспроизведению

Попытка сделать ванильную печку

**Comment by SpeeeDCraft** [comment]
Исправлено в dev, будет в след. обновлении.
