### ISSUE TITLE
About More Red

### ISSUE THREAD

**Issue by serialtasted** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#37]
### Your Question

Hi there,
Sorry to make seperate posts but after sending the last one, I remebered this, and you had alredy close the other one.
Have you seen this mod that fills a bit the gap that project red left when using redstone?
https://www.curseforge.com/minecraft/mc-mods/more-red

**Comment by SpeeeDCraft** [comment]
Yes, this is a cool mod, we will add it, thanks for the suggestion.
