### ISSUE TITLE
Ножницы не стригут овец из TFC (медные) - возможно и другие так-же не работают

### ISSUE THREAD

**Issue by Latom-alex** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#38]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Сервер

### Новые миры

Да

### Ожидаемое поведение

https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/150847107/715e9564-feca-4642-9e8f-d8d737de2f2e

![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/150847107/3855be9a-7848-4b50-961b-17e5ec1ef39e)

По какой-то причине ножницы не стригут Овец. Хз по какой но должно работать наоборот.

### Фактическое поведение

.

### Действия по воспроизведению

.

**Comment by SpeeeDCraft** [comment]
К сожалению не помню, как работало на 1.12, возможно нужно +/- приручить овец, но я сомневаюсь, короче нужно больше исследовать этот вопрос

**Comment by SpeeeDCraft** [comment]
Нужно кормить овцу 3 дня подряд, тогда ее можно будет подстричь, не баг.
