### ISSUE TITLE
Добавить мод All-In-One, Macaw's Mods for TerraFirmaCraft

### ISSUE THREAD

**Issue by C0ffo** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#39]
### Версия используемого модпака

Последняя

### Связанная проблема

Я всегда расстраиваюсь когда нет мостов...

### Ваше решение

Если бы я мог ходить по мосту было бы заебись

**Comment by C0ffo** [comment]
https://www.curseforge.com/minecraft/mc-mods/macaws-for-terrafirmacraft - ссылка на курсфорд мода

**Comment by SpeeeDCraft** [comment]
Добавлено
