### ISSUE TITLE
Добавить разнообразие кораблей TerraFirmaShips

### ISSUE THREAD

**Issue by Floda28** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#40]
### Версия используемого модпака

0.0.5

### Связанная проблема

Добавить разнообразие кораблей для атмосферы 

### Ваше решение

Предлагаю добавить мод который был на 1.18 н а корабли 
Добавляю ссылку : https://www.curseforge.com/minecraft/mc-mods/terrafirmaships

### Дополнительная информация

https://www.curseforge.com/minecraft/mc-mods/terrafirmaships

**Comment by Andrei-Mudrov-archmage** [comment]
Yes! Yes! YES! YES! YES

**Comment by SpeeeDCraft** [comment]
Добавлено
