### ISSUE TITLE
Добавить компютеры !

### ISSUE THREAD

**Issue by Floda28** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#41]
### Версия используемого модпака

Ласт

### Связанная проблема

Доабвить пк в игру для разных решений 
(Можно выпилить от туда шахтеров)

### Ваше решение

https://www.curseforge.com/minecraft/mc-mods/cc-tweaked/files?page=1&pageSize=20

**Comment by SpeeeDCraft** [comment]
Уже добавили
