### ISSUE TITLE
Del home and rtp and call

### ISSUE THREAD

**Issue by igooogwork** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#42]
### Версия используемого модпака

1.20(0.0.5)

### Связанная проблема

Disabled home and rtp and call
Только кровать, телепорт один == смерть.
Прежде всего, если загружаешь чанки rtp, у животных начинает отсчитываться таймер до их гибели.
Во-вторых, при использовании rtp исчезнут кусты и еда в радиусе его действия, и тебе все равно на окружающий ландшафт и его красоту.
В-третьих, логистика также представляет интерес. Вместо того чтобы просто установить два дома и телепортироваться между ними до усталости, можно разнообразить геймплей используя повозки и животных.
Не обязательно ограничиваться монотонным прыжком между двумя точками или бесконечным путешествием в шахту.

### Ваше решение

disabled-commands:
    - home
    - rtp
    - call

### Дополнительная информация

Это легко реализуемо.

**Comment by SpeeeDCraft** [comment]
Это штуки у модов, на квесты/команды, которые мы решили для теста использовать, уже убедились в том, что они не очень хорошо работают, в след. обновлении они будут удалены на старые которые всегда мы использовали, там этих команд нет.

**Comment by igooogwork** [comment]
Я про то что они не особо и нужны вообще как по мне. Но решать вам.
