### ISSUE TITLE
Невозможно создать Jacks

### ISSUE THREAD

**Issue by Yorodoshi** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#44]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Сервер

### Новые миры

Да

### Ожидаемое поведение

Должны были создаться Jacks

### Фактическое поведение

Из-за конфликта рецептов длинного стержня и Jacks создался длинный стержень.

### Действия по воспроизведению

https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/08dd2997-63d3-42b3-8cf9-eb8fdd43bb30

**Comment by SpeeeDCraft** [comment]
Исправлено в dev, будет в след. обновлении.
