### ISSUE TITLE
Повторный поджег костра.

### ISSUE THREAD

**Issue by igooogwork** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#45]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Server

### Новые миры

Нет

### Ожидаемое поведение

Ожидал что смогу поджечь повторно потухший костер.
Взял в руки примитивное огниво навел на костер.
Поджег.

### Фактическое поведение

Ожидал что смогу поджечь повторно потухший костер.
Взял в руки примитивное огниво навел на костер.
Вместо возможности потереть огниво я попадаю в интерфейс костра.

### Действия по воспроизведению

Подождите пока костер потухнет киньте туда бревно и попытайтесь поджечь.
Поджечь можно но если начать заряжать огниво на другом блоке и не отпуская перевести на костер.

### Дополнительная информация

Это вызвано тем что огниво открывает интерфейс, вместо использования функции поджигания.

**Comment by Yorodoshi** [comment]
С шифтом поджигай и всё
