### ISSUE TITLE
Пирит и Сырая железная руда не плавятся в горне?

### ISSUE THREAD

**Issue by C0ffo** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#46]
### Ваш вопрос

Это баг или нормально?

**Comment by SpeeeDCraft** [comment]
Баг на сервере, в очередной раз, в локалке все отлично. Исправим ближе к вечеру.

**Comment by C0ffo** [comment]
Держу вкурсе,желтый лимонит,гематит тоже не плавятся,я так понял не плавятся все грег руды железные

**Comment by SpeeeDCraft** [comment]
Пон, пон, вечером фикс

**Comment by C0ffo** [comment]
Пофиксили? что-то не работает до-сих пор

**Comment by SpeeeDCraft** [comment]
Только что на сервере проверили и все работает
