### ISSUE TITLE
Крафт ступки по ванильному камню

### ISSUE THREAD

**Issue by C0ffo** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#47]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Официальный сервер ТФГ

### Новые миры

Да

### Ожидаемое поведение

Думал скрафтить ступку

### Фактическое поведение

Но в итоге крафт только через ванильные камни
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/151227314/7a5bdf2f-c619-48d1-8c0d-2c43c09b202f)

### Действия по воспроизведению

.

**Comment by SpeeeDCraft** [comment]
fixed in dev
