### ISSUE TITLE
Глина никак не выпекается в кирпич

### ISSUE THREAD

**Issue by C0ffo** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#48]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Официальный сервер ТФГ

### Новые миры

Да

### Ожидаемое поведение

Хотел пожарить глину на кирпичи 

### Фактическое поведение

Нигде не жарятся,те - просто не вставляется глина как от на костер 
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/151227314/37b811ed-c01b-4a79-a837-3a25d8cd2984)

### Действия по воспроизведению

.

**Comment by SpeeeDCraft** [comment]
Из глины сначала делаются глиняные кирпичи, а только потом жарятся, вот бы REI кто открыл

**Comment by C0ffo** [comment]
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/151227314/bbd1700d-5679-4bbe-ae84-cf1b1e3dbee0)
да?
