### ISSUE TITLE
Нету крафта PBF (Примитивной большой печки)

### ISSUE THREAD

**Issue by C0ffo** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#49]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Официальный сервер ТФГ

### Новые миры

Да

### Ожидаемое поведение

Смотрел крафты предметов для развития но крафта Primitive Blast Furnace нету

### Фактическое поведение

Вот я типа кликаю 
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/151227314/7b32b8fa-0fa5-4d05-992f-3e517c812854)

### Действия по воспроизведению

.

**Comment by FriendlyCube** [comment]
а че хотел, сталь будешь плавить только через тфк

**Comment by C0ffo** [comment]
> а че хотел, сталь будешь плавить только через тфк

Так она по квестам идет...
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/151227314/4f10795a-1c5c-48fb-b363-92ce8e8a94e4)

**Comment by SpeeeDCraft** [comment]
И не должно, квесты будут перерабатываться в будущем. Сейчас частично только ветка тфк готова.
