### ISSUE TITLE
Нынешнее пати не работает совсем...

### ISSUE THREAD

**Issue by Yorodoshi** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#51]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Сервер

### Новые миры

Да

### Ожидаемое поведение

Принятие приглашение, возможность его отправлять и прочее.

### Фактическое поведение

Нельзя принять приглашение пати, расформировать пати и прочее.

### Действия по воспроизведению

Создал пати и на этом всё закончилось(

**Comment by SpeeeDCraft** [comment]
Исправлено в 0.0.8, ожидайте.
