### ISSUE TITLE
Косы|Лопаты|Мотыги не работают

### ISSUE THREAD

**Issue by Yorodoshi** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#52]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Сервер/одиночная

### Новые миры

Да

### Ожидаемое поведение

Ломание AOE травы и листвы

### Фактическое поведение

Они ломают по 1 блоку и не работают на листву

### Действия по воспроизведению

Косы не работают

### Дополнительная информация

https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/fc40bbca-e2b3-4b35-9abe-373b36f8422e

**Comment by SpeeeDCraft** [comment]
И снова разрабы гт, насрали, напишу им на гит

**Comment by Yorodoshi** [comment]
Мотыги не вспахивают, лопаты не делают дорожек

**Comment by SpeeeDCraft** [comment]
Фикс гт поправит: https://github.com/GregTechCEu/GregTech-Modern/commit/b4147126ed60966b563bd9199e3350dbd87949e2

**Comment by SpeeeDCraft** [comment]
Исправлено нашей кровью в 0.1.0
