### ISSUE TITLE
Нет крафтов у этих предметов из разных металлов: мясницкие ножи, напильники, майнинг молоты, киянки, ступки

### ISSUE THREAD

**Issue by Yorodoshi** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#53]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Сервер|Одиночная 

### Новые миры

Да

### Ожидаемое поведение

Рецепты литья или хотя бы экструдирования мясницкие ножи, напильники, майнинг молоты, киянки, ступки

### Фактическое поведение

Нет рецептов

### Действия по воспроизведению

У других предметов, допустим ножей есть рецепты, через литьё, экструдер и прочее, а у многих (Медь, висмутовая|обычная|чёрная бронза, стерлингово серебро, розовое золото, кованное железо, красная и синяя сталь) мясницких ножей нет

### Дополнительная информация

![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/00ce77bf-a0fa-4aaf-b314-f4ed41d01da4)
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/e08fbf71-beee-482d-b2f8-5a745c036fe3)

**Comment by SpeeeDCraft** [comment]
Дубликат #59
