### ISSUE TITLE
Отсутствие крафтов Steam Hammer и булыжниковых плит (для деревяной помпы) 

### ISSUE THREAD

**Issue by C0ffo** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#56]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Официальный сервер ТФГ

### Новые миры

Да

### Ожидаемое поведение

Смотрел крафты на будущее

### Фактическое поведение

Крафта Steam Hammer вообще небыло + без постоянной воды в паровую эру опасно заходить)

### Действия по воспроизведению

.

**Comment by SpeeeDCraft** [comment]
Окей, сенкс за тикет
