### ISSUE TITLE
Пила не пилит

### ISSUE THREAD

**Issue by Yorodoshi** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#57]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Сервер|одиночная

### Новые миры

Да

### Ожидаемое поведение

Пила пилит дерево

### Фактическое поведение

Пила не пилит дерево

### Действия по воспроизведению

Пила тупая(

### Дополнительная информация

![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/536e55e5-7209-49fa-b1f0-0d7777ea5253)

**Comment by SpeeeDCraft** [comment]
Я сколько раз должен повторить о том, что с гт инструментами беда и их фикс разрабы уже залили в грег, им осталось только на курсе опубликовать, но каждый день я получаю тикеты с багами гт инструментов, охх..
