### ISSUE TITLE
Каменный уголь безполезен

### ISSUE THREAD

**Issue by Yorodoshi** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#58]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Сервер|Одиночная 

### Новые миры

Да

### Ожидаемое поведение

Уголь будет использоваться как топливо

### Фактическое поведение

Каменный уголь не работает, приходится использовать только древесный

### Действия по воспроизведению

Каменный уголь гавно
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/35abaccb-a791-4055-97a4-2270285f2b03)

### Дополнительная информация

Не работает что в угольной кузне, что при создании крицы

**Comment by C0ffo** [comment]
> ![image](https://user-images.githubusercontent.com/151227314/284679375-1e60077a-97a0-48b7-a0a6-5ed35b14c9ba.png) ![image](https://user-images.githubusercontent.com/151227314/284679513-9d14eb7a-9c52-48ba-97bc-15daa153b03e.png)

Понял?

**Comment by C0ffo** [comment]
Хотя вот этот уголь каменный на горн не идет как древесный,так что предлагаю чтобы он там тоже использовался

**Comment by SpeeeDCraft** [comment]
Мда, это пофиксим
