### ISSUE TITLE
Нету крафта напильника для грега

### ISSUE THREAD

**Issue by C0ffo** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#59]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Официальный сервер ТФГ

### Новые миры

Да

### Ожидаемое поведение

Хотел скрафтить

### Фактическое поведение

Не скрафтил

### Действия по воспроизведению

Пытка скрафтить

**Comment by SpeeeDCraft** [comment]
Какое ахерительное описание, бро, ты может скрины прикрепишь или еще че, не крафтится в каком смысле? голова + палка, просто голова, ни то ни другое, никакой инфы

**Comment by C0ffo** [comment]
Тупанул да 
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/151227314/9ce3449a-f805-43a1-9036-4d996972da96)
Типа кликаю по напильнику и нету крафта головы
Кстати еще добавлю что нету крафта латунных блоков для стекла
а оно нужно для крафта экстрактора
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/151227314/558cab8f-cb4c-470e-b37d-a1e68ade8a2a)

**Comment by Latom-alex** [comment]
Нету крафтов напильников в прямом смысле (делается только 1 напильник из Алюминия) - и то он делается через машины на ULV LV Уровне

Напильник нельзя выковать на наковальне - нету крафта
Нету крафта напильника из большенство металлов (только алюминий) 

https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/150847107/281a4244-70b9-4ae8-9e2f-4a044ddf42a5


https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/150847107/8f4445b6-f41a-4265-ada2-d939eb4b1172

**Comment by SpeeeDCraft** [comment]
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/52341158/bc6fd2b0-3f27-4674-8d1d-45591ef083ec)
Вроде сейчас все нормально, я про рецепт, <металл> -> (Extruder) -> оголовье

На счет ковки гт оголовий, их и вправду нужно добавить.

Короче исправлено, будет в некст патче.
