### ISSUE TITLE
При попытке попить из бурдюка игра вылетает

### ISSUE THREAD

**Issue by So0vey** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#60]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

официальный сервер

### Новые миры

Да

### Ожидаемое поведение

После тяжкого труда по сбору ослиных мочевых пузырей для создания бурдюков на всю тиму хотелось наконец утолить свою жажду из свежесозданного бурдюка

### Фактическое поведение

Майнкрафт сделал паунс в окно

### Действия по воспроизведению

Стою на базе, наполняю бурдюк, пытаюсь попить и вылет

### Дополнительная информация

[crash-2023-11-21_21.17.09-client.txt](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/files/13429899/crash-2023-11-21_21.17.09-client.txt)
[crash-2023-11-21_21.29.29-client.txt](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/files/13429900/crash-2023-11-21_21.29.29-client.txt)

**Comment by SpeeeDCraft** [comment]
Дубликат #61
