### ISSUE TITLE
Игра крашится, когда пьешь из бурдюка

### ISSUE THREAD

**Issue by Yorodoshi** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#61]
### Версия используемого модпака

0.9

### Среда запуска

Сервер|Одиночная 

### С какой стороны краш

Клиент

### Новые миры

Да

### Действия по воспроизведению

Пытался выпить из полного бурдюка

### Отчет о сбое

[crash-2023-11-21_21.41.11-client.txt](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/files/13429937/crash-2023-11-21_21.41.11-client.txt)
[crash-2023-11-21_21.39.32-client.txt](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/files/13429938/crash-2023-11-21_21.39.32-client.txt)
[crash-2023-11-21_21.37.50-client.txt](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/files/13429940/crash-2023-11-21_21.37.50-client.txt)

**Comment by SpeeeDCraft** [comment]
Не могу воспроизвести, бегаю, пью из бурдюков и не крашит, проверь на новой версии которая выйдет, если крашит переоткрой, пока закрыто.
