### ISSUE TITLE
TFC животные не горят если их поджечь

### ISSUE THREAD

**Issue by Yorodoshi** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#62]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Сервер|Одиночная 

### Новые миры

Да

### Ожидаемое поведение

Животное сгорит и даст жареное мясо

### Фактическое поведение

Животное невосприимчиво к огню

### Действия по воспроизведению

Пождёг осла

### Дополнительная информация

![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/8a3b9996-ee40-49b0-8a04-f866f5e16738)

**Comment by SpeeeDCraft** [comment]
Лучше бы вы это не мне сюда тонной вываливали, а на гит тфк

**Comment by SpeeeDCraft** [comment]
Исправлено в новом тфк, будет в след обнове (0.1.0)
