### ISSUE TITLE
Порченная еда невосприимчива к температуре

### ISSUE THREAD

**Issue by Yorodoshi** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#64]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Сервер|Одиночная 

### Новые миры

Да

### Ожидаемое поведение

Еда исчезнет либо превратиться в пепел или типо того

### Фактическое поведение

Она нагревается до белеет до блеска и ничего не происходит...
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/31c6944c-e843-4507-b65c-c60967045e36)

### Действия по воспроизведению

Подождал пока сгниёт и нагрел

**Comment by SpeeeDCraft** [comment]
Фишка тфк, я че с этим сделаю, снова пол мода переписывать ради фичи, которой будут пользоваться 1.5 человека, короче лоу приорити, дальше посмотрим

**Comment by SpeeeDCraft** [comment]
Добавлены рецепты в gt машинах на раскрафт в биомассу и куски биомассы
