### ISSUE TITLE
Коксовая печь невозможна до пара

### ISSUE THREAD

**Issue by Yorodoshi** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#65]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Сервер|Одиночная 

### Новые миры

Да

### Ожидаемое поведение

Раскалить неготовый кирпич в угольной яме и получить Coke Oven Brick

### Фактическое поведение

Нельзя сделать коксовую печь до паровой эры(
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/d91481a2-3c81-4f16-bf5e-1a95d9c19e21)

### Действия по воспроизведению

Кирпичи не каляться

**Comment by C0ffo** [comment]
Розачарую,даже если сможеш сжарить то тебе нужны пластины железа с простого а не с горна,то-есть + печка паровая и + паровой молот ибо в наковальне такое железо не куется никак

**Comment by C0ffo** [comment]
Я вот бы уже сделал да мне этих пластин нехватает) нет крафта наковальни для молота

**Comment by SpeeeDCraft** [comment]
Да в курсе, емае
