### ISSUE TITLE
Железные слитки нельзя расплавить в железо лол

### ISSUE THREAD

**Issue by Yorodoshi** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#67]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Сервер|Одиночная 

### Новые миры

Да

### Ожидаемое поведение

Железные слитки можно плавить и под ними написанно 144мб Liquid iron

### Фактическое поведение

![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/ea4d3376-b203-4b83-adcf-d74cb4ba27d3)

### Действия по воспроизведению

Ну вот так

### Дополнительная информация

Добавьте рецепт плавки

**Comment by Yorodoshi** [comment]
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/c5c6e6a0-b9c1-4582-b448-ffd6dc16fd25)

**Comment by SpeeeDCraft** [comment]
> ![image](https://user-images.githubusercontent.com/128903188/284831783-c5c6e6a0-b9c1-4582-b448-ffd6dc16fd25.png)

Вот ты вот это скинул, я должен сидеть угадывать, что не так, если ты подразумевал, плавку свинца в тфк металл, то на 1.20 такого металла в тфк нет.
