### ISSUE TITLE
Дюп ЛЮБЫХ ТФК металлов через незаконченную броню

### ISSUE THREAD

**Issue by Yorodoshi** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#68]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Сервер|Одиночная 

### Новые миры

Да

### Ожидаемое поведение

Выковывая из слитка 144мб любую незаконченную часть брони мы получаем часть брони с 144мб

### Фактическое поведение

Выковывая из слитка 144мб любую незаконченную часть брони мы получаем часть брони с 576мб X4 дюп лол

### Действия по воспроизведению

Получаем 1 слиток любого металла, из него мы дюпаем любое количество слитков

**Comment by SpeeeDCraft** [comment]
Эх, дюпайте пока можно
