### ISSUE TITLE
Просьба добавить некоторые моды.

### ISSUE THREAD

**Issue by So0vey** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#69]
### Версия используемого модпака

Да

### Связанная проблема

Хотелось бы попросить установить в клиент сборки 2 дополнительных мода:

Один из них жизненно необходим пожилым ведрам на 2х герцовых пнях, как у моей жены.
А именно, мод Smooth Boot: https://www.curseforge.com/minecraft/mc-mods/smooth-boot-reloaded/files
Т.к. мне лень писать описание, да и за меня его написали вот оно:  немного ускорит процесс загрузки игры и сделает его более плавным, теперь игра при загрузке не будет потреблять 100% процессора, а значит не будет лагов \ прерываний музыки \ подвисаний курсоров в других приложениях.

,Из тестов этого мода в одиночной игре: майнкрафт не зависает ни на долю секунды на ее ноутбуке. Вообще ведро уникальное(от слова кал). На зависнуть ему требуется мгновение, но вот чтобы расчехлиться, ему нужно времени значительно больше. 

(Опять же этот моды ставить вам или нет, не зависит, поставлю я его ей. НО, это просто забота о игроках  с похожими ведрами, которые на знают о существовании такого мода.)

Второй мод Soduim(Rubidium ) Extra: https://www.curseforge.com/minecraft/mc-mods/rubidium-extra
Добавит множество тончайших настроек для содиума(тоесть рубидиума), подчернку:
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/127132701/8e8d6863-7ffa-4ca3-a907-693fadc2990b)
То есть возможность некоторые частицы отключать полностью.
Например на моей загруженной базе идет постоянный спам одних частиц. Я могу поставить частицы минимум, но пострадают частицы от, допустим воды, а я такого не хотел. Ну вот за этим нужен содиум экстра.

(Как и в первом моде, ставить такое решать именно вам. Но это же мастхев QoF момент!)

### Ваше решение

Я все сказал) 
Поэтому расскажу тупейший анекдот:
— Что у нaс нa обед?
— Фaсолевый суп.
— А нa второе?
— Активировaнный уголь.

**Comment by SpeeeDCraft** [comment]
Тема, не знал, что smoothboot обновился до 1.20, короче ставим
