### ISSUE TITLE
Кривая механика физики опор

### ISSUE THREAD

**Issue by Latom-alex** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#70]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Сервер

### Новые миры

Да

### Ожидаемое поведение

Блять чё за хуйня с физикой опор? Просто пол шахты обвалилось в 3 пизды из за того что я в другом конце сделал обвал. чё за прикол не понял. над опорами были везде блоки. да и не должно быть так вообще.

https://discord.com/channels/400913133620822016/1167131478459695186/1177364749361631332
https://discord.com/channels/400913133620822016/1167131478459695186/1177364337602592828

### Фактическое поведение

.

### Действия по воспроизведению

.

### Дополнительная информация

.

**Comment by FriendlyCube** [comment]
во перых это надо писать тфк разрабам а во вторых ты копал блоки которые не были в радиусе действия опор, + к этому это как в реал лайф, не думай шо в сказку попал)

**Comment by SpeeeDCraft** [comment]
Шиза
