### ISSUE TITLE
Добавить рецепты производства муки в дробителе

### ISSUE THREAD

**Issue by Yorodoshi** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#71]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Сервер|Одиночная 

### Новые миры

Да

### Ожидаемое поведение

Муку из крупы можно получить лишь допотопным способом на жёрновах, но технологичный дробитель на это не способен(
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/a327ced3-3142-439b-89c9-30457e87a7ba)

### Фактическое поведение

![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/dd604060-3a44-47dd-8b64-591103c62fd6)

### Действия по воспроизведению

Вот так вот

### Дополнительная информация

Добавить рецепт для всех круп (Ячменная, овсяная, ржаная, рисовая, пшеничная, кукурузные зёрна)

**Comment by SpeeeDCraft** [comment]
Да, надо бы, спасибо за тикет
