### ISSUE TITLE
Невозможность сделать стекло, надо сделать параллельный крафт

### ISSUE THREAD

**Issue by Yorodoshi** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#72]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Сервер|Одиночная 

### Новые миры

Да

### Ожидаемое поведение

![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/abbbddfe-1ca9-4ffc-86d1-4efca4891885)
что вот этот способ будет работать

### Фактическое поведение

Я всеми правдами неправдами пытался хоть что-то туда высрать, как написано в книжечке, с латунными пластинами, блоками, что только не делала, как только не кликал. не вышло.

### Действия по воспроизведению

Ну не работает

### Дополнительная информация

Предлагаю:
1. Сделать этот крафт со всеми видами TFC песка а не с ванильным
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/ca4ae99e-7d4e-4ace-b58c-2950047d8cb1)
2. Решить проблему с напильниками для того чтобы сделать стекло по этому рецепту:
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/14a7aa14-3e6f-46c5-8d02-911b3e780be1)
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/9860937f-9b73-473d-a733-56019c1a7bf1)
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/ed809a20-a989-4fb4-8a75-95df34d5675a)

**Comment by SpeeeDCraft** [comment]
В книге все было написано правильно, просто не воспринимались блоки латуни. Теперь же и блоки GTCEu учитываются, то есть нужно сделать эту яму из латунных блоков и все будет отливаться. После отливки блока стекла его нужно выкопать специальной пилой, чтобы блок стекла выпал.

![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/52341158/7d701a3e-b1c3-4aa9-9c84-930a3aa65b3e)
