### ISSUE TITLE
Тонны испорченных продуктов нуждаются в переработке !!!

### ISSUE THREAD

**Issue by Yorodoshi** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#73]
### Версия используемого модпака

0.9

### Связанная проблема

Ничего кроме как выкинуть с ними я не могу, мне от этого грустно и я храню их, надеясь что они мне понадобятся для чего-нибудь.
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/a9f4885d-74ae-447e-a919-9c821c1eda23)
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/47d6158f-effb-4eea-8902-c6d8f59eb5df)

### Ваше решение

1. Необходимо добавить рецепты производства метана в центрифугу. (если уж очень запариться можно сделать расчёт по количеству метана в зависимости от питательности этой еды, как и в 1.12)
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/f5263a32-f6e4-4f25-bcfd-ee55f5bff8f8)
2. Добавить рецепты производства биомассы из ТФК растений:
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/5b179c16-9a8a-4e8e-be99-79ace09285e4)
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/a6bf1897-e909-4136-b3d9-6f7222a859e6)
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/a2ecc826-4195-44fa-ad92-e177853fd9ed)

**Comment by SpeeeDCraft** [comment]
Дубликат #64
