### ISSUE TITLE
Русификатор ГрегТеча

### ISSUE THREAD

**Issue by So0vey** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#75]
### Версия используемого модпака

Кто?

### Связанная проблема

Перевода нету 

### Ваше решение

Alex, Kuzya и Soovey сидели переводили мод. вот вам перевод:

Версия перевода еще далеко не полная, но перевели очень многое 
[ru_ru.json](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/files/13462760/ru_ru.json)

**Comment by FriendlyCube** [comment]
это надо кидать разрабам мода который переводите

**Comment by SpeeeDCraft** [comment]
Сделайте PR, положив файл в: kubejs/assets/gtceu/lang/<file_name>

![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/52341158/d4dfd275-e8e1-4272-ae00-ed7b3ca909d7)

и пуште туда работу которую сделали, как доделаете замерджу
