### ISSUE TITLE
Краш игры при соединении трубы с помпой из GregTech

### ISSUE THREAD

**Issue by Latom-alex** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#76]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Сервер

### Новые миры

Да

### Ожидаемое поведение

Я понимаю что Грег еще не полностью сделан но всё-же вот отчёты об ошибке. Возможно потом не будут проблемы с поиском краша игры
[crash-2023-11-25_05.01.21-server.txt](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/files/13462809/crash-2023-11-25_05.01.21-server.txt)
[crash-2023-11-25_05.03.18-server.txt](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/files/13462810/crash-2023-11-25_05.03.18-server.txt)

### Фактическое поведение

.

### Действия по воспроизведению

Возьмите трубу \ над ней поставьте бочку из TFC с водой или без \ Возьмите Pump GregTech на 64mb\t поставьте ее к верху трубы (что-бы она была под бочкой) возьмите ключ и соедините трубу с бочкой. 

Краш мира пермаметный (Без возможности загрузить заново. т.к воспроизводится краш)

### Дополнительная информация

.

**Comment by SpeeeDCraft** [comment]
А мне то что пишете, на гит грега и вперед

**Comment by SpeeeDCraft** [comment]
Щас пытался протестировать, но в шагах описано все непонятно, почему не прикрепить скрин?
Бочку например нельзя ставить на трубу. 
Короче тестируйте в новой версии, если крашит, снова сюда отписываем и переоткрываем, пока что закрыто.
