### ISSUE TITLE
Почему в игре отсутствуют показ рецептов золотых слитков как таковых ? 

### ISSUE THREAD

**Issue by Yorodoshi** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#77]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Сервер|Одиночная 

### Новые миры

Да

### Ожидаемое поведение

Хотел хранить золото в слитках

### Фактическое поведение

А слитков то нету в игре как таковых

### Действия по воспроизведению

добавьте, а то бред какой-то

**Comment by Yorodoshi** [comment]
Я получил слиток положив руду в печку, такого рецепта REI не показывало. Это скорее всего связанно с тем что это слиток из TFC а не из GT
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/3e129f44-9c13-4ad5-8bdb-36b399b42cae)

**Comment by SpeeeDCraft** [comment]
Да, ты прав, очень странно, что ты получит тфкшный слиток, мдам, ладно, починим
