### ISSUE TITLE
Дерьмодюп "Brick Wooden Form"

### ISSUE THREAD

**Issue by Yorodoshi** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#80]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Сервер|Одиночная 

### Новые миры

Да

### Ожидаемое поведение

Что скрафтив 8х3 кирпичей с помощью 8 формочек я получу обратно 8 формочек

### Фактическое поведение

![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/1ccb22f4-b91d-4779-81a1-9eda5fd6c40c)
По итогу с каждых 8 крафтов кирпичей я получаю 7 ТЫСЯЧ ЕБАНЫХ ДЕРЕВЯННЫХ РАМОК

### Действия по воспроизведению

![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/adae0757-30c4-48b5-9202-830aaa94e588)
крафтим 8 штук (тестил только по 8) получаем 24 кирпичика и 7 ТЫСЯЧ рамок.

### Дополнительная информация

Я не ебу почему так происходит. Но видимо там какая-то проблема с крафтами.

https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/937a8a28-b6a7-4f37-a500-eb2b4a7d8207

https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/8a08e6e1-3f84-4054-a2fd-4f26d36a8829

**Comment by So0vey** [comment]
Грегтеч альфа...

**Comment by Yorodoshi** [comment]
Баг ушёл на 0.1.0
