### ISSUE TITLE
GT инструменты имеют уровень добычи ниже чем положено материалу

### ISSUE THREAD

**Issue by Yorodoshi** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#81]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Сервер|Одиночная 

### Новые миры

Да

### Ожидаемое поведение

Что GT кирка из красной стали будет по уровню => TFC кирке из чёрной стали что нужна для добычи изумрудной гранитной руды

### Фактическое поведение

![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/e43f0cd8-764a-4502-b1fd-30f06fa9132a)
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/4c492894-5bc3-4aa3-ad29-f2bdb0bf8da4)

Кирка из красной стали GT хуже по уровню кирке из чёрной стали TFC

### Действия по воспроизведению

Кривые значения уровни добычи кирок

**Comment by SpeeeDCraft** [comment]
Баг не с кирками, а баг с рудой тфк, которая почему-то решила появиться в мире, исправлено.
