### ISSUE TITLE
Где крафт ванильного ведра ??

### ISSUE THREAD

**Issue by Yorodoshi** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#83]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Сервер|Одиночная 

### Новые миры

Да

### Ожидаемое поведение

Был крафт через TFC и через GT

### Фактическое поведение

По итогу удалили оба крафта
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/8abf67aa-065b-4992-8143-6d369edf7998)

### Действия по воспроизведению

нету

### Дополнительная информация

Добавьте обратно крафт хоть какой-нить

**Comment by SpeeeDCraft** [comment]
Ченджлог читаем, глазки протираем
