### ISSUE TITLE
Зачем появилось 2 вида слитков ? Раньше всё кроме золота - Грег, сейчас в перемешку

### ISSUE THREAD

**Issue by Yorodoshi** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#84]
### Ваш вопрос

![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/4cf7ac8b-c738-4af8-bc46-d8bea32ac6c7)
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/9b424b5b-7ba6-414f-aa7b-585bc0714e70)

**Comment by SpeeeDCraft** [comment]
При каких условиях удалось получить слитки стали из tfc?

**Comment by SpeeeDCraft** [comment]
Плюсом раньше медь была из тфк, золото из тфк и железо из тфк

**Comment by Yorodoshi** [comment]
> При каких условиях удалось получить слитки стали из tfc?

Просто из отливочной формы вынул

**Comment by SpeeeDCraft** [comment]
Удивительно, ладно, в некст патче будет исправлено, в любом случае эти слитки взаимозаменяемые и проблем с использованием не будет
