### ISSUE TITLE
Куб справился с рюкзаками

### ISSUE THREAD

**Issue by So0vey** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#87]
### Ваш вопрос

Во первых они все еще не красятся. 
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/127132701/80aee12a-9b85-4fbb-ac08-6ab4c3efab96)
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/127132701/0dfe446e-030d-4409-b362-c81afa033ce5)
Во вторых что за прикол:

![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/127132701/52fc9fbc-4d5e-4c04-aedf-b742e27103dd)
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/127132701/5b678e6e-6065-4580-bb44-c0810ba85597)

Идем далее
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/127132701/62f8c428-526b-4cb7-a753-b8e38a5f3033)
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/127132701/1ac982c5-3dd2-4c2e-806a-01bd1269139d)

Далее
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/127132701/e3cd55bf-0e1f-42b1-96dd-c54ef47eee45)
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/127132701/a8bed99a-1478-4eef-b60c-7dfe3e6014ff)

Далее
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/127132701/18e4adc7-11a9-42b3-96a7-35bcd91d29c3)
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/127132701/59c67f4d-2417-4b90-9364-ff8b62a7620b)

Это все. Это как?

**Comment by So0vey** [comment]
При том, что теги прекрасно понятно

**Comment by So0vey** [comment]
Про покрас рюзкаков сори зря быканул

**Comment by SpeeeDCraft** [comment]
Дак что не так то?

**Comment by So0vey** [comment]
Это типо апгрейд их?

**Comment by SpeeeDCraft** [comment]
Типо да

**Comment by So0vey** [comment]
а, так просто в тегах железный рюкзак
