### ISSUE TITLE
Немноооожечко изменить правила спавна мобов.

### ISSUE THREAD

**Issue by So0vey** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#90]
### Версия используемого модпака

Последняя

### Связанная проблема

Враждебные мобы... они повсюду. 
Поскольку в тфк факела тухнут, комнаты в домах и зданиях перестают освещаться и в них появляется нечисть.
Также в пещерах под землей появляются мобы, которые никак не контактируют с игроками, которые на поверхности. Но нагружают сервер и подъедают тпс.

Ситуация следующая: Игрок стоит на поверхности (обычно это 100 и выше ). 
Мобы появляются на расстоянии от X и Y блоков от игрока.  Обычно эти показатели зависят от настроек сервера.
На расстоянии свыше Y мобы не влияют на сервер и кушают тпс.

### Ваше решение

Ограничить высоту спавна мобов так, чтобы мобы не появлялись в шахтах, пока игроки на поверхности. Тоесть задать интервал спавна нечести по высоте от -60 (бедрок) до +40 (Допустим эта высота будет высчитана как 100-Y(примем за 60))

В итоге враждебные мобы не могут заспавнится на высоте выше +40.
 
Игроки которые на бегают на поверхности не спавнят нечисть. Нечисть не грузит сервер. Нечисть не лезет из темных комнат домов и подвалов. И самое главное НЕ ИГРАЕТ МУЗЫКУ В ПЕЩЕРЕ ПОД ТВОЕЙ БАЗОЙ. 

Но как только игрок спускается в шахту мобы в пещерах попадают в зону прогруза и начинают спавнится ниже +40. 

Способ реализации предложу чуть позже, если найду.

**Comment by So0vey** [comment]
Вот решение без применения плагинов https://www.curseforge.com/minecraft/mc-mods/in-control

**Comment by So0vey** [comment]
config\incontrol\spawn.json

[
{
"minheight": 60,
"hostile": true,
"result": "deny"
}
]

**Comment by SpeeeDCraft** [comment]
Юзай другие средства освещения, на счет нагрузки на серв, у нас стоит мод EntityCulling, у клиента на производительность кол-во мобов которых он не видит не влияет, что же до сервера, возможно на обработку AI, что то да уходит, короче не приоритетно и не нужно
