### ISSUE TITLE
сделать так, чтобы булыжниковые плиты не дефали от камнепада 

### ISSUE THREAD

**Issue by FriendlyCube** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#91]
### Версия используемого модпака

0.1.0

### Связанная проблема

игроки могут задефать себя от камнепада в пещерах с помощью булыжникоых полублоков

### Ваше решение

возможно можно добавить булыжник полублоки в список блоков которые ломаются когда на них падают камни, или же в список который заставит их осыпаться как камень

### Дополнительная информация

![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/112543401/17c924ca-5cd6-4e39-ba09-8441ab1c7941)

**Comment by SpeeeDCraft** [comment]
Исправлено
