### ISSUE TITLE
Неверное определение даты просрочки в крафте муки в TG дробителе 

### ISSUE THREAD

**Issue by Yorodoshi** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#92]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Сервер|Одиночная 

### Новые миры

Да

### Ожидаемое поведение

Что перемалывая хорошее зерно я получу норм муку как в жерновах
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/f6af9fe5-12f3-498f-9271-1ba03078bd3a)
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/57a5bc59-4afc-4b94-9f00-1582e1d25dba)

### Фактическое поведение

![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/273cb63d-3fc6-42ef-9b95-d29b40bec09f)
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/9e0b46b3-6e5a-4474-b868-e5a3c5dbb570)

### Действия по воспроизведению

Если брать идеально новое зерно, тогда мука будет не протухшей, НО если зерно чуть полежало то мука просроченная выходит. 

### Дополнительная информация

Я думаю что проблема в формуле изменения даты просрочки в мацераторе, нужно перенести формулу с жёрнов ПОЛНОСТЬЮ на мацератор

**Comment by SpeeeDCraft** [comment]
Не смог повторить, взял зерно, промотал 40 дней, кинул в масератор, на выходе не протухшая пыль, закрываю
