### ISSUE TITLE
Жидкостный бойлер не принимает топливо

### ISSUE THREAD

**Issue by a22kat** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#97]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

сервер

### Новые миры

Да

### Ожидаемое поведение

-

### Фактическое поведение

Жидкостный бойлер не работает, не принимает топливо через трубу или ведро. В частности креозот, говорят и другое топливо тоже.

### Действия по воспроизведению

-

**Comment by SpeeeDCraft** [comment]
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/52341158/369d6e25-f095-4be4-827c-b1a4044152ac)
Я наверное кого-то удивлю, но по жидкости можно нажать U и увидеть рецепты и как видим грег сам не добавляет рецепт креозота в мелком жидкостном бойлере, но добавляет в большой.

Он как раз принимает разные жидкости.

**Comment by a22kat** [comment]
Удиви тогда еще раз, и расскажи так на чем же работают маленькие жидкостные бойлеры?

**Comment by SpeeeDCraft** [comment]
Допустим лава
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/52341158/79a7805f-1912-4041-bc55-ee90cf659609)
