### ISSUE TITLE
Можно сделать крафт нормальных слитков из ТФК слитков ?

### ISSUE THREAD

**Issue by Yorodoshi** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#98]
### Версия используемого модпака

0.1.1

### Связанная проблема

После обновы мои 456 слитков меди, 803 слитка золота, 14 слитка стали превратились в вафлю(((
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/962125b4-baae-4985-a805-0710347b6ac3)
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/51248298-d4bd-4b72-b8ae-694e31b955d3)
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/64703f51-b726-4618-af5b-fe48c285ded3)

### Ваше решение

Сделать крафты по типу ТФК слиток -> норм слиток
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/a3431a37-decb-4c48-aa05-1112bf145656)
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/d0a3256e-de63-4180-a6ef-e8420a46fc1e)
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/9569535f-78f2-4d65-a434-028beef04512)

### Дополнительная информация

Или же добавить скрипт который автоматически превращает любые слитки в ГТ, (я видел такое на Hi-Tech серверах)

**Comment by SpeeeDCraft** [comment]
Ну да, конечно, костыли нам делать еще, если играешь на сервере, попроси в свободное время меня или Xikaro, зайдем и переделаем твои слитки через креатив, если в локалке, тогда еще проще, просто креатив вруби и переделай слитки.
Бета же, но почему-то все считают, что это релиз
