### ISSUE TITLE
Неадекватные крафты

### ISSUE THREAD

**Issue by Yorodoshi** [TerraFirmaGreg-Team/TFG-Modpack-1.20.x#99]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Сервер|Одиночная 

### Новые миры

Да

### Ожидаемое поведение

Как раньше из стали

### Фактическое поведение

Это слишком, это неадекватно.
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/a65fd07e-c80a-4f83-a9ce-9598c1a2672f)
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/e6dd2df4-1afb-4e19-bc12-dec32402ea94)

### Действия по воспроизведению

.

### Дополнительная информация

Сделайте обратно, это нереально так играть.

**Comment by FriendlyCube** [comment]
гений
так на 1 12 было

**Comment by FriendlyCube** [comment]
плюс лв уровень вообще идет после криейта, в теории ты с помощью криейта сможешь автоматизировать крафт стали

**Comment by Yorodoshi** [comment]
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/3d4b7fb9-b67a-49a9-a0a4-9df73364ff9d)
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/f35d40f8-fab0-41bc-9988-01194bff9c50)
Синяя сталь это EV крафты, какой ЛВ корпус

**Comment by FriendlyCube** [comment]
а на деле мы в бете, гоу просто смиришься, сборка постепенно приходит в итоговый вариант + радуйся, пластины по 144 а не по 288 единиц материала

**Comment by C0ffo** [comment]
> гений так на 1 12 было

На 1.12.2 было в версии 2.0,щяс 4.40 - тоесть сто лет назад

**Comment by C0ffo** [comment]
> а на деле мы в бете, гоу просто смиришься, сборка постепенно приходит в итоговый вариант + радуйся, пластины по 144 а не по 288 единиц материала

Уже сделали по 144?я ебашил все под 288

**Comment by FriendlyCube** [comment]
> 
> Уже сделали по 144?я ебашил все под 288

чекай фотку где он навелся на пластину

**Comment by FriendlyCube** [comment]
> 
> На 1.12.2 было в версии 2.0,щяс 4.40 - тоесть сто лет назад

вот это не понял

**Comment by C0ffo** [comment]
> > На 1.12.2 было в версии 2.0,щяс 4.40 - тоесть сто лет назад
> 
> вот это не понял

Беру за данные вот это
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/151227314/4ea7b91b-f18c-4ce5-a13d-1fefced8fe73)

**Comment by C0ffo** [comment]
> ну так крафт не менялся с тех пор

Эмммм я играл 3 месяца назад нa 1.12.2 ver 4.36 дошел до МВ и там все лв корпуса со стали делались

**Comment by FriendlyCube** [comment]
как давно я не заходил туда...

**Comment by SpeeeDCraft** [comment]
Ля, что ты несешь, какой EV уровень, EV, это титан, красную и синюю сталь можно сделать в тфк даже, эх, люди, люди
